[project]
name = "stm32f4_rtt"
scan_root = "Core"
recursive = true
extensions = [
    ".h",
    ".c",
]

[artifacts]
elf = "build/Debug/stm32f4_rtt.elf"
hex = ""
bin = ""

[generation]
out_dir = "."
header_name = "rat_gen.h"

[ratd]
text_id = 255

[ratd.source]
auto_scan = true
scan_timeout_ms = 300
last_selected_addr = "127.0.0.1:19021"

[ratd.behavior]
reconnect = "1s"
schema_timeout = "3s"
buf = 256
reader_buf = 65536

[ratd.outputs.jsonl]
enabled = true
path = ""

[ratd.outputs.foxglove]
enabled = false
ws_addr = "127.0.0.1:8765"
